#!/bin/bash

# Function to add a user
add_user() {
    read -p "Enter username to add: " username
    sudo useradd "$username" && echo "User $username added."
}

# Function to delete a user
delete_user() {
    read -p "Enter username to delete: " username
    sudo userdel "$username" && echo "User $username deleted."
}

# Function to list users
list_users() {
    echo "Listing all users:"
    cat /etc/passwd
}

# Menu
echo "Select an option:"
echo "1. Add User"
echo "2. Delete User"
echo "3. List Users"
read -p "Choice: " choice

case $choice in
    1) add_user ;;
    2) delete_user ;;
    3) list_users ;;
    *) echo "Invalid choice" ;;
esac


