name: hellow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hellow to me
        run: echo "$USER"

      - name: say hellow to username
        run: echo "this is me"

